<?php

namespace Tests\Unit;

use App\Models\User;
use Illuminate\Support\Str;
use Tests\TestCase;

class AuthTest extends TestCase
{
    private $username;
    private $password;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->username = fake()->userName();
        $this->password = Str::random(8);
    }

    public function test_register()
    {
        $data = [
            'first_name' => fake()->firstName(),
            'last_name' => fake()->lastName(),
            'username' => fake()->userName(),
            'password' => $this->password,
            'password_confirmation' => $this->password,
        ];
        $response = $this->post(route('register'), $data);

        $response->assertSessionHas('success');
        $response->assertRedirect(route('loginView'));
    }

    public function test_login()
    {
        User::factory()->create([
            'username' => $this->username,
            'password' => $this->password,
        ]);
        $data = [
            'username' => $this->username,
            'password' => $this->password,
        ];

        $response = $this->post(route('login'), $data);

        $response->assertRedirect(route('articleList'));
    }
}
